spring:
  application:
    name: market-catalog-ms

  jpa:
    hibernate:
      ddl-auto: none # liquidBase
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        show_sql: false

  # Disable auto liquidbase , use manually config instead
  liquibase:
    enabled: false
