spring:
  application:
    name: market-catalog-ms

  jpa:
    hibernate:
      ddl-auto: none # liquidBase
    open-in-view: false
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
